### ISSUE TITLE
Problem with /releasetools/ota_from_target_files

### ISSUE THREAD

**Issue by ishtiaque9** [MiCode/patchrom_tools#9]
I've encountered this particular error while trying to run ota_target_from_phone.

The terminal error is given below:

Build full ota package: /home/ishtiaque/patchrom/xblade/stockrom.zip
Traceback (most recent call last):
  File "/home/ishtiaque/patchrom/tools/releasetools/ota_from_target_files", line 76, in <module>
    import common
  File "/home/ishtiaque/patchrom/tools/releasetools/common.py", line 42, in <module>
    OPTIONS.search_path = os.path.join(os.environ["$PORT_ROOT"], "tools");
  File "/usr/lib/python2.7/UserDict.py", line 23, in **getitem**
    raise KeyError(key)
KeyError: '$PORT_ROOT'

As you can see, it seems there's a certain issue with the $PORT_ROOT thing. Please look into it and provide solution. Do I need to edit envsetup.sh in any way?

**Comment by programmerlapar** [comment]
it seems didn't run
. build/envsetup.sh 
try run it firstly and ota target from phone again

**Comment by ishtiaque9** [comment]
I actually did run .build/envsetup.sh and it worked. However, I found out
this other thing. Whenever I need to run any 'make' commands or
ota_target_from_phone, I have to run the envsetup.sh each time separately.
Why is that, could you please tell me?

On Thu, Jan 2, 2014 at 6:36 PM, Firmansyah Otoluwa <notifications@github.com

> wrote:
> 
> it seems didn't run
> . build/envsetup.sh
> try run it firstly and ota target from phone again
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/MiCode/patchrom_tools/issues/9#issuecomment-31450277
> .

## 

Ahmed Ishtiaque

**Comment by iBotPeaches** [comment]
You have to initialize the build environment. That is required in tons of build setups.

**Comment by ghost** [comment]
I know it is late but running

# source build/envsetup.sh

removed all my usues :100:
